ShopList/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShopList.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public DateTime Created { get; set; }
        public DateTime Updated { get; set; }
        public string Owner_Id { get; set; }
        public int Cat_Id { get; set; }
        public int SubCat_Id { get; set; }
        public int Loc_Id { get; set; }
        public int Img_Id { get; set; }

        [ForeignKey("Img_Id")]
        public virtual ImageUpload Image { get; set; }
        [ForeignKey("Loc_Id")]
        public virtual Location Location { get; set; }
        [ForeignKey("SubCat_Id")]
        public virtual SubCategory SubCategory { get; set; }
    }
}

ShopList/Models/PostViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Models
{
    public class CreatePostViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string PostName { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string PostDescription { get; set; }
        [Required]
        [Display(Name = "Category")]
        public string Cat { get; set; }
        [Required]
        [Display(Name = "Price")]
        public double Price { get; set; }
        [Required]
        [Display(Name = "SubCategory")]
        public int? SelectedSubCatId { get; set; }
        public IEnumerable<SelectListItem> SubCats { get; set; }
        [Required]
        [Display(Name = "Location")]
        public int? SelectedLocId { get; set; }
        public IEnumerable<SelectListItem> Locs { get; set; }
        [Display(Name = "Image")]
        public string File { get; set; }
    }

    public class PostDetailsViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string PostName { get; set; }
        [Required]
        [Display(Name = "Description")]
        public string PostDescription { get; set; }
        [Required]
        [Display(Name = "Category")]
        public string Cat { get; set; }
        [Required]
        [Display(Name = "Price")]
        public double Price { get; set; }
        [Required]
        [Display(Name = "SubCategory")]
        public int? SelectedSubCatId { get; set; }
        public IEnumerable<SelectListItem> SubCats { get; set; }
        [Required]
        [Display(Name = "Location")]
        public int? SelectedLocId { get; set; }
        public IEnumerable<SelectListItem> Locs { get; set; }
        [Display(Name = "Image")]
        public string File { get; set; }
    }

    public class SubCatViewModel
    {
        public IList<Post> Posts { get; set; }
    }

}

ShopList/Controllers/PostController.cs
using Microsoft.AspNet.Identity;
using ShopList.Extensions;
using ShopList.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Controllers
{
    public class PostController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Details(int id)
        {
            var post = db.Posts.Where(p => p.Id == id).FirstOrDefault();
            var img = db.Images.Where(i => i.Id == post.Img_Id).FirstOrDefault();
            ViewBag.UserId = User.Identity.GetUserId();
            ViewBag.FilePath = img.FilePath;
            return View(post);
        }

        public ActionResult Index(int loc_id)
        {
            var posts = db.Posts.Where(p => p.Loc_Id == loc_id);
            ViewBag.Posts = posts.ToList().OrderByDescending(c => c.Created);
            return View();
        }

        public ActionResult UserIndex(string id)
        {
            var posts = db.Posts.Where(p => p.Owner_Id == id);
            ViewBag.Posts = posts.ToList().OrderByDescending(c => c.Created);
            return View();
        }

        public ActionResult Create()
        {
            var userId = User.Identity.GetUserId();
            if (userId == null)
            {
                return RedirectToAction("Login");
            }
            var model = new CreatePostViewModel
            {
                SubCats = GetSubCats(),
                Locs = GetLocs()
            };
            
            return View(model);

             
        }

        [HttpPost]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                var uploadedFile = Request.Files[0];
                string filename = $"{DateTime.Now.Ticks}{uploadedFile.FileName}";
                var serverPath = Server.MapPath(@"~\Uploads");
                var fullPath = Path.Combine(serverPath, filename);
                uploadedFile.SaveAs(fullPath);

                var image = new ImageUpload
                {
                    File = filename,
                    PostId = post.Id
                };
                db.Images.Add(image);

                var subCat_Id = int.Parse(Request.Form["SelectedSubCatId"]);
                post.SubCat_Id = subCat_Id;
                var subCat = db.SubCats.Find(subCat_Id);
                post.Img_Id = image.Id;
                post.Loc_Id = int.Parse(Request.Form["SelectedLocId"]);
                post.Cat_Id = subCat.CategoryId;
                post.Description = Request.Form["PostDescription"];
                post.Name = Request.Form["PostName"];
                post.Price = double.Parse(Request.Form["Price"]);
                post.Created = DateTime.Now;
                post.Owner_Id = User.Identity.GetUserId();
                post.Updated = DateTime.Now;
                db.Posts.Add(post);

                db.SaveChanges();
                return RedirectToAction("Details", new { id = post.Id});
            }


            return View(post);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            var post = db.Posts.Where(p => p.Id == id).First();
            if (post.Owner_Id == User.Identity.GetUserId())
            {
                return View();
            }
            return RedirectToAction("Index");
        }   
        

        [HttpPost]
        [Authorize]
        public ActionResult DeletePost(int id)
        {


            var post = db.Posts.Where(p => p.Id == id).First();
            if (post.Owner_Id == User.Identity.GetUserId())
            {
                db.Posts.Remove(post);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
            
        }

        private IEnumerable<SelectListItem> GetSubCats()

        {

            var subCats = db.SubCats
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.Id.ToString(),
                                    Text = x.Cat.CatTag + " - " + x.Title
                                });

            return new SelectList(subCats, "Value", "Text");
        }

        private IEnumerable<SelectListItem> GetLocs()
        {

            var locs = db.Locs
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.Id.ToString(),
                                    Text = x.Locale
                                });

            return new SelectList(locs, "Value", "Text");
        }
    }
}

ShopList/Controllers/SubCatController.cs
using ShopList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Controllers
{
    public class SubCatController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int loc_Id, int subCat_Id, string viewOrder, string view)
        {
            ViewBag.Loc_Id = loc_Id;
            var loc = db.Locs.SingleOrDefault(l => l.Id == loc_Id);
            ViewBag.locale = loc.Locale;

            ViewBag.SubCat_Id = subCat_Id;
            var subCat = db.SubCats.SingleOrDefault(s => s.Id == subCat_Id);
            ViewBag.sub = subCat.Title;

            ViewBag.View = view;
            var posts = db.Posts.Where(p => p.SubCat_Id == subCat_Id && p.Loc_Id == loc_Id);

            if (viewOrder == "high")
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(p => p.Price);
            }

            else if (viewOrder == "low")
            {
                ViewBag.Posts = posts.ToList().OrderBy(p => p.Price);
            }

            else
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(c => c.Created);
            }
            return View();
        }

        public ICollection<Post> GetPosts(int loc_Id, int subCat_Id)
        {
            var posts = db.Posts.Where(p => p.Loc_Id == loc_Id && p.SubCat_Id == subCat_Id);
            return posts.ToList();
        }
    }
}

ShopList/Views/Post/Create.cshtml
@model ShopList.Models.CreatePostViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Create Your Post</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedSubCatId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.SelectedSubCatId, Model.SubCats, new { htmlAttributes = new { @class = "form-control text-box single-line" } })
                </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedLocId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedLocId, Model.Locs, new { htmlAttributes = new { @class = "form-control text-box single-line" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PostName, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostName, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PostDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostDescription, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", placeholder = "0.00" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2", placeholder = "your img filepath" })
            <div class="col-md-10">
                <input type="file" name="File" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

ShopList/Views/Post/Delete.cshtml
@model ShopList.Models.Post

<div class="container">

    @using (Html.BeginForm())

    {
        <h2>Delete this Post?</h2>
        <h3>@Model.Name</h3>
        <p>Price: $@Model.Price</p>
        <p>Location: @Model.Location.Locale</p>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

</div>

ShopList/Views/Post/Details.cshtml
@model ShopList.Models.Post


<div class="container">
    <div class="col-lg-8 text-center">
        <h2>
            @Model.Name - $@Model.Price - (@Model.Location.Locale)
        </h2>
    </div>
        <div class="col-lg-8">
            <img class="thumb" src="@Model.Image.FilePath" />
        </div>
    <div class="col-lg-8">
        <h4>
            @Model.Description
        </h4>
    </div>
    <div class="col-lg-8 text-center">
        @if (ViewBag.UserId == Model.Owner_Id)
        {
            @Html.ActionLink("Delete Your Post", "Delete", new { id = Model.Id }) 
        }
        | @Html.ActionLink("Back", "Index", "SubCat", new { subCat_Id = Model.SubCat_Id , viewOrder = "", loc_Id = Model.Location.Id , view = "thumb"}, new { })
    </div> 
    

</div>

ShopList/Views/Post/UserIndex.cshtml
<br/>
<br />
<div class="container">
    @foreach (var item in ViewBag.Posts)
    {
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <img class="thumb" src="@item.Image.FilePath" />
                </div>
                <div class="col-lg-6 text-center">
                    <h2>
                        @item.Name - $@item.Price - (@item.Location.Locale)
                    </h2>
                    <h4>
                        @item.Description
                    </h4>
                    <h4>
                        @Html.ActionLink("Delete This Post", "Delete", new { id = item.Id })
                    </h4>
                </div>
            </div>
        </div>
        <hr/>
    }
</div>