ShopList/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShopList.Models
{
    public class HomeListViewModel
    {
        public ICollection<Category> Cats { get; set; }
        public ICollection<SubCategory> SubCats { get; set; }
    }


}

ShopList/Controllers/CategoryController.cs
using ShopList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Controllers
{

    public class CategoryController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        /*
        public ActionResult Index(int page, int maxThumbs, int catId)
        {
            var allPosts = db.Posts.Where(c => c.Cat_Id == catId).OrderByDescending(c => c.Created);
            int showPage = page;
            int showThumbs = maxThumbs;
            int skipThumbs = page-- * maxThumbs;
            List<Post> posts = allPosts.Skip(skipThumbs).Take(showThumbs).ToList();
            ViewBag.posts = posts;
            return (ViewBag.posts);
        }
        */

        public ActionResult Index(int loc_Id, int cat_Id, string viewOrder)
        {
            var posts = db.Posts.Where(p => p.Cat_Id == cat_Id && p.Loc_Id == loc_Id);
            if (viewOrder == "high")
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(p => p.Price);
            }
            else if (viewOrder == "low")
            {
                ViewBag.Posts = posts.ToList().OrderBy(p => p.Price);
            }
            else
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(c => c.Created);
            }
            return View();
        }
    }
}

ShopList/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using ShopList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Controllers
{
    
    public class HomeController : Controller
    {
        public static ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult HomeList(int loc_Id)
        {
            ViewBag.loc_Id = loc_Id;
            var model = new HomeListViewModel
            {
                Cats = GetCats(),
                SubCats = GetSubCats()  
            };
            var loc = db.Locs.Where(x => x.Id == loc_Id).FirstOrDefault();
            ViewBag.loc_Name = loc.Locale;
            return View(model);

        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            if (userId == null)
            {
                var model = new ChooseLocationViewModel
                {
                    Locs = GetLocs()
                };

                return View(model);
            }
            var userInstance = db.Users.Where(u => u.Id == userId).FirstOrDefault();
            if (userInstance == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var u_loc_Id = userInstance.PrefLocId;
            return RedirectToAction("HomeList", "Home", new { loc_Id = u_loc_Id });
            
            
        }

        public ActionResult LocList()
        {
            var model = new ChooseLocationViewModel
            {
                Locs = GetLocs()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult ChooseLocation()
        {
            var loc_Id = int.Parse(Request.Form["SelectedLocId"]);
            return RedirectToAction("HomeList", "Home", new { loc_id = loc_Id });
        }

        private ICollection<Category> GetCats()
        {
            var cats = db.Cats.ToList();
            return cats;
        }

        private ICollection<SubCategory> GetSubCats()
        {
            var subCats = db.SubCats.ToList();
            return subCats;
        }

        private IEnumerable<SelectListItem> GetLocs()
        {

            var locs = db.Locs
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.Id.ToString(),
                                    Text = x.Locale
                                });

            return new SelectList(locs, "Value", "Text");
        }
    }
}

ShopList/Controllers/SubCatController.cs
using ShopList.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopList.Controllers
{
    public class SubCatController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int loc_Id, int subCat_Id, string viewOrder, string view)
        {
            ViewBag.Loc_Id = loc_Id;
            var loc = db.Locs.SingleOrDefault(l => l.Id == loc_Id);
            ViewBag.locale = loc.Locale;

            ViewBag.SubCat_Id = subCat_Id;
            var subCat = db.SubCats.SingleOrDefault(s => s.Id == subCat_Id);
            ViewBag.sub = subCat.Title;

            ViewBag.View = view;
            var posts = db.Posts.Where(p => p.SubCat_Id == subCat_Id && p.Loc_Id == loc_Id);

            if (viewOrder == "high")
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(p => p.Price);
            }

            else if (viewOrder == "low")
            {
                ViewBag.Posts = posts.ToList().OrderBy(p => p.Price);
            }

            else
            {
                ViewBag.Posts = posts.ToList().OrderByDescending(c => c.Created);
            }
            return View();
        }

        public ICollection<Post> GetPosts(int loc_Id, int subCat_Id)
        {
            var posts = db.Posts.Where(p => p.Loc_Id == loc_Id && p.SubCat_Id == subCat_Id);
            return posts.ToList();
        }
    }
}

ShopList/Views/Home/HomeList.cshtml
@model ShopList.Models.HomeListViewModel
@{
    ViewBag.Title = "HomeList";
}

<div class="container">
    <h1>@ViewBag.loc_Name Listings</h1>
    @foreach (var item in Model.Cats)
    {
        <div class="col-sm-6 col-md-4">
             <h3>@Html.ActionLink(item.CatTag,"Index","Category", new {loc_Id = ViewBag.loc_Id, viewOrder = "", cat_Id = item.Id}, new { })</h3>
                    @foreach (var sc in Model.SubCats)
                    {
                        if (sc.CategoryId == item.Id)
                        {
                            <p>---@Html.ActionLink(sc.Title, "Index", "SubCat", new { loc_Id = ViewBag.loc_Id, viewOrder = "", subCat_Id = sc.Id, view = "thumb"}, new { })</p>
                        }
                    }

        </div>
    }
</div>

ShopList/Views/Home/Index.cshtml
@model ShopList.Models.ChooseLocationViewModel

<div class="container">
    @using (Html.BeginForm("ChooseLocation", "Home", FormMethod.Post))
    {
    <div class="col-lg-8">
        <h2>
            Choose Your City
        </h2>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SelectedLocId, Model.Locs, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Confirm Choice" class="btn btn-default" />
        </div>
    </div>
    }
    
</div>

ShopList/Views/Home/LocList.cshtml
@model ShopList.Models.ChooseLocationViewModel

<div class="container">
    @using (Html.BeginForm("ChooseLocation", "Home", FormMethod.Post))
    {
        <div class="col-lg-8">
            <h2>
                Choose Your City
            </h2>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedLocId, Model.Locs, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirm Choice" class="btn btn-default" />
            </div>
        </div>
    }

</div>